### ISSUE TITLE
Limit causes error on query

### ISSUE THREAD

**Issue by RegEM** [feliperohdee/smallorange-dynamodb-client#1]
Hi, thanks for sharing your code.

I ran into issue where I am trying to limit the number of queries, but I get an error. It appears to error if there are more items found than my limit setting. My goal is to limit to just one item based upon the time.

For example I am requesting a time of 2017-08-03T20:24, which returns 25 items. I receive the following error if the limit is set less than 24. 

Observer got an error: TypeError: Cannot match against 'undefined' or 'null'.

Any ideas or suggestions? Thanks, Richard

**Comment by RegEM** [comment]
Still a problem I believe, but for now  I ended up skirting the issue by having the limit big enough, and using a '.first()' in the chain. 

Hope you get a chance to look into it.

**Comment by feliperohdee** [comment]
Hi @RegEM, I'm going to see soon, thank you for report!

**Comment by RegEM** [comment]
Hi. 
Sorry, the error was seen in the Lambda logs, and is long gone. error was concise, and as stated previously.
If I get a chance, I'll redo.

Request was something like this:
          request
             .limit(24) 
          // observer throws error when 1 
          // or if less than num of returned values if when .limit(1000)
          // this eventTimeValue returns 25 items, and error thrown if limit is less
             .addPlaceholderName({keyName: 'key', eventTimeName: 'eventTime'})
             .addPlaceholderValue({keyValue: keyValueVar, eventTimeValue: '2017-08-03T20:24'})
             .query('#keyName = :keyValue AND begins_with(#eventTimeName, :eventTimeValue)')
             .takeUntil(stop$)
             .subscribe(observer);

Since running into the error, I've added .first(). before the subscribe. And changed the begins_with() to a between(). limiting the result by using the .first(). Not ideal, but ok for now.
This request is now sub to another observable request of array data, for my variables. 
Not sure if I was using the .takeUntil(stop$) at the time of the error.

**Comment by feliperohdee** [comment]
Hey @RegEM, we're trying to reproduce this error, but without success =(. We're trying with the request below, your request is something like that?

```javascript
describe.only('issue #1', () => {
	before(done => {
		Observable.range(0, 50)
			.mergeMap(n => request.insert({
				namespace,
				id: `id-issue-${n}`,
				message: `message-${n}`
			}, true))
			.subscribe(null, null, done);
	});
	
	it('should dont throw observer w/ limit 1', done => {
		request
			.limit(1)
			.addPlaceholderName({
				namespace: 'namespace',
				id: 'id'
			})
			.addPlaceholderValue({
				namespace,
				id: 'id-issue'
			})
			.query('#namespace = :namespace AND begins_with(#id, :id)')
			.toArray()
			.subscribe(response => {
				expect(response.length).to.be.equal(1);
			}, done, done);
	});

	it('should dont throw observer w/ limit 25', done => {
		request
			.limit(25)
			.addPlaceholderName({
				namespace: 'namespace',
				id: 'id'
			})
			.addPlaceholderValue({
				namespace,
				id: 'id-issue'
			})
			.query('#namespace = :namespace AND begins_with(#id, :id)')
			.toArray()
			.subscribe(response => {
				expect(response.length).to.be.equal(25);
			}, done, done);
	});

	it('should dont throw observer w/ limit 100', done => {
		request
			.limit(100)
			.addPlaceholderName({
				namespace: 'namespace',
				id: 'id'
			})
			.addPlaceholderValue({
				namespace,
				id: 'id-issue'
			})
			.query('#namespace = :namespace AND begins_with(#id, :id)')
			.toArray()
			.subscribe(response => {
				expect(response.length).to.be.equal(50);
			}, done, done);
	});
});
```

result:
```
src/Request
query
  issue #1
    ✓ should dont throw observer w/ limit 1
    ✓ should dont throw observer w/ limit 25
    ✓ should dont throw observer w/ limit 100
    
  3 passing (2s)
```

**Comment by RegEM** [comment]
Hi felipe,
Yes my request was quite simple. So I was surprised of the error.
However, it looks like I must be doing something wrong in my code. The request is within a button event, so perhaps that is a factor. 
I will look into it much closer, and let you know if I determine the cause.
I see reference online to 'destructuring' as possible cause, and also bundle.js (which I do). So maybe the problem is related to one of these issues.
Thanks for checking. Closing...

**Comment by feliperohdee** [comment]
Yes @RegEM, you're a right, this kind of error is caused by destructing objects, and we looked for the error in possibles destructors, however, the tests are covering this situations. If you find any error, please open an issue, thank u!

**Comment by RegEM** [comment]
Thanks for the tip. I have much to learn. 
I am happy to have ran across your code.
