### ISSUE TITLE
chaining scanIndexForward

### ISSUE THREAD

**Issue by RegEM** [feliperohdee/smallorange-dynamodb-client#2]
Please help felipe

I can't seem to chain .scanIndexForward(false) to a query. Just getting, 'is not a function'.

Thanks, Richard

**Comment by RegEM** [comment]
Interestingly I can get my result with:
.limit(1000000) // I have less items
.query(...).last()
But it takes a while

**Comment by feliperohdee** [comment]
Hi @RegEM , you can use 

```javascript
  dynamoDb.table({...})
  	.desc()
  	.query({...})
  	.subscribe(nextFn, errFn, completeFn);
```

**Comment by RegEM** [comment]
What I was hoping worked is something like this;
    requestforlastitem
       .limit(anyvalue)
       .scanIndexForward(false)
       .addPlaceholderName({keyName: 'key'})
       .addPlaceholderValue({keyValue: keyValueVar})
       .query('#keyName = :keyValue')
       //newest
       .first()
       .subscribe(observer_newest);

but get error, ''.scanIndexForward is not a function''

Not sure what I'm missing

**Comment by RegEM** [comment]
Ok. I guess I need to back up some, use less queries, and instead use more getItems! Was trying to use a chainsaw when a toothpick would've been more appropriate.

**Comment by feliperohdee** [comment]
you can just replace the ScanIndexForward by desc, this call changes the ScanIndexForward at request

**Comment by RegEM** [comment]
ok thank you. That fixes my problem. Sorry to have missed desc() in the readme.
I had to add the import for Request too. Not sure if that was proper way, but works.

**Comment by RegEM** [comment]
Thanks, sure do appreciate your help.
By looking at the responses in devtools, I have a bit better understanding how this all works now, so I think I will probably reorganize my code quite a bit. Probably will change my lambda function that creates my table too.
